version: "2.0"
services:
    smtp:
        build: FakeSMTP/.
        ports:
            - "25:25"
    #smtp:
    #  image: python
    #  command: python -m smtpd -n -c DebuggingServer 0.0.0.0:25
    #  ports:
    #    - "25:25"
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: dev
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: myapp

#    rmq:
#        image: "rabbitmq:management"
#        hostname: "rmq"
#        ports:
#            - '15672:15672'
    app:
        build: sat-app/.
        ports:
            - "8080:8080"
        environment:
            APP_DB_HOST: db:3306
            APP_WEB_HOST: web
            APP_SMTP_HOST: smtp
        depends_on:
            - "smtp"
            - "db"
    web:
        build: sat-web/.
        ports:
            - "8000:8000"
        depends_on:
            - "app"
